name: Build, Test and deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Copy to DigitalOcean droplet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: garygrossgarten/github-action-scp@release
        with: 
          local: /
          remote: /var/www/arpankc.com/public_html
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}     